name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make
    - uses: actions/upload-artifact@v4
      with:
        path: puppyfetch
        name: puppyfetch-linux-x86_64
